name: 📖 Document
description: File a new document/issue
title: "[DOCUMENT] <title>"
labels: [Document]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this or similar document.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Document location
      description: What type of document location?
      multiple: false
      options:
        - Repository
        - Wiki
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: A concise but full description of the proposed new document.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the new document!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
