name: 🦶 Feature
description: File a new feature/issue
title: "[FEATURE] <title>"
labels: [Feature]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this or similar feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Details
      description: A concise but full description of the proposed new feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the new feature!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
