name: 🪴 Refactor
description: File an refactor/issue
title: "[REFACTOR] <title>"
labels: [Feature, Refactor]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Issue Type
      description: What type of feature?
      multiple: false
      options:
        - Feature
        - Documentation
        - Testing
        - Workflow
    validations:
      required: true
  - type: input
    id: feature
    attributes:
      label: Issue Ref
      description: "Which issue does this relate to?"
      placeholder: "Example: https://github.com/rusty-apps/`REPOSITORY`/issues/`ISSUE_NUMBER` "
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: A concise but full description of the proposed refactorisation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the change!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
