name: 🤔 Testing
description: File a new testing/issue
title: "[TESTING] <title>"
labels: [Feature, Testing]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this or similar feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: feature
    attributes:
      label: Feature
      description: "Which feature does this relate to?"
      placeholder: "Example: https://github.com/rusty-apps/`REPOSITORY`/issues/`ISSUE_NUMBER` "
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: A concise but full description of the proposed new testing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the new testing!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
